services:
  etcd:
    image: bitnamilegacy/etcd:latest
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://${VM3_IP}:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${VM3_IP}:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_NAME=vm3
      - ETCD_INITIAL_CLUSTER=vm3=http://${VM3_IP}:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=keycloak-etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/bitnamilegacy/etcd
    restart: unless-stopped

volumes:
  etcd_data:




